### ISSUE TITLE
Change password

### ISSUE THREAD

**Issue by mkotzjan** [cwansart/Zento#18]
A user should be able to change his or her password. Add this to the popover (#6)

**Comment by cwansart** [comment]
Shouldn't this be done in the editProfile action?

**Comment by apollo7321** [comment]
Should we add the possibility to change the address?

**Comment by apollo7321** [comment]
We should add a popover or so if the passwords don't match. See editProfile.blade.php at line 64.

**Comment by mkotzjan** [comment]
Which adress? EMail?
