### ISSUE TITLE
Add search functionality

### ISSUE THREAD

**Issue by mkotzjan** [cwansart/Zento#20]
Lists (User/Exam/Seminars) should be searchable by e.g. name, date, ...

**Comment by apollo7321** [comment]
Where do you want to add the search bar? To each view or to the main.blade.php?

**Comment by mkotzjan** [comment]
Better to every view... Appointments don't need a search box

**Comment by mkotzjan** [comment]
Oh it does, what do I know ;) we have to think about for what we can search. Does it make sense to search for a firstname in exams?

**Comment by apollo7321** [comment]
Sure, what else would you search for? There are only dates for the exams instead, since they don't have a title.
