### ISSUE TITLE
Filter for displaying users that have passwords (that can login)

### ISSUE THREAD

**Issue by mkotzjan** [cwansart/Zento#57]
This could be a little Icon or something. Every User should see the other trainer

**Comment by apollo7321** [comment]
You can't display the password, it's encrypted.

**Comment by mkotzjan** [comment]
No no no, listen to me my friend! You know that only user with password are reale "user". It would be nice to see other users or "trainer"

**Comment by apollo7321** [comment]
Ah... So you meant displaying only those that have passwords, not _their_ passwords. ;-) I got it buddy!

**Comment by mkotzjan** [comment]
Ya Bro, exactly!
