### ISSUE TITLE
Dropdown for logout and profile

### ISSUE THREAD

**Issue by mkotzjan** [cwansart/Zento#6]
Add a bootstrap popover containing "change password" and "logout"

**Comment by apollo7321** [comment]
http://www.w3schools.com/bootstrap/tryit.asp?filename=trybs_popover&stacked=h

**Comment by mkotzjan** [comment]
http://jsfiddle.net/vqT5f/2/

**Comment by apollo7321** [comment]
Popover doesn't work, because it doesn't allow HTML and so on. We'll need to use a dropdown. I'm not going to add all the HTML to a HTML attribute. The popover is not made for that. If you like the style then apply the CSS.
