### ISSUE TITLE
Date format in error message of User.Create

### ISSUE THREAD

**Issue by mkotzjan** [cwansart/Zento#77]
The date format of the validation error message of User.Create is wrong.
This is the message:

```
Es gab ein paar Probleme:

Geburtstag muss ein Datum vor dem 2016-06-29 sein.
Eintrittsdatum muss ein Datum vor dem 2016-06-30 sein.
```

The validation should warn if a birthday is not before the actual date and if an entry date is after today.

**Comment by apollo7321** [comment]
Closed https://github.com/cwansart/Zento/commit/8af58b5e2a29b1a0ce9481efdd8842e7f00e29b0
