### ISSUE TITLE
Modal for edit view on member/exam/seminar

### ISSUE THREAD

**Issue by mkotzjan** [cwansart/Zento#8]
The edit view should be displayed inside a modal

**Comment by apollo7321** [comment]
I used the wrong issue number. I created modal dialog for creating, so Issue #15 
@ChaosBelcebub  do we really want modal dialog for editing? I'd rather add an edit button to the users show view so you first get an overview that you're editing the right user. Just check /users/1/edit and tell me, if a modal dialog is really necessary?
